name: example-flow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: check server-info
        run: lsb_release -a
      - name: display wording
        run: echo hello ${{ github.actor }}
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: check server-info
        run: ver
      - name: display wording
        run: echo hello ${{ github.actor }}
